### ISSUE TITLE
Links aren’t clickable in the Bluesky iOS app

### ISSUE THREAD

**Issue by heyajulia** [LoranKloeze/teletekstbot-net#1]
At least in the iOS app, the URLs aren’t clickable, and post text isn’t selectable, so you either have to type out the URL manually or use Live Text, which is quite cumbersome. I think it would be much nicer if the URL were clickable or if the title itself were a link. (I know the latter is possible because `@kottke.org` is doing it.)

**Comment by LoranKloeze** [comment]
Thx, a PR or other proposal to fix it would be very welcome :)

**Comment by LoranKloeze** [comment]
Extra notes:
- The links are clickable in the web application of BlueSky

**Comment by heyajulia** [comment]
The link in [this post](https://bsky.app/profile/teletekstbot.bsky.social/post/3k4xvphnrg42v) isn’t clickable for me on the web, but [this post’s link is](https://bsky.app/profile/teletekstbot.bsky.social/post/3k4y2lk56f62d), and is pretty much what I had in mind, but it was posted before I opened this issue, and I swear I didn’t see it until now. Either way, we can close this now unless there’s still something missing.

**Comment by LoranKloeze** [comment]
I am sorry... it turns out I had the old application still live when you found this bug. The new and now live version as this already fixed. Thank you for noticing it.
