### ISSUE TITLE
Short titles end up with trailing periods

### ISSUE THREAD

**Issue by LoranKloeze** [LoranKloeze/teletekstbot-net#5]
![image](https://github.com/LoranKloeze/teletekstbot-net/assets/12978070/a12f177e-16cb-41d4-b90f-6310f5957909)

Those periods should be removed.

**Comment by mrhoeve** [comment]
When there's one period at the end of the title, that should stay?

**Comment by LoranKloeze** [comment]
Nope, because the NOS doesn't use any trailing periods in the title at the pages themselves too.

**Comment by LoranKloeze** [comment]
Fixed in https://github.com/LoranKloeze/teletekstbot-net/commit/a592a6dd7829c1105561fdf471e5b73cec8cea7b

**Comment by mrhoeve** [comment]
Recent posts don't seem to have this issue, so can't really reproduce it. I did make a code change to fix this so it won't happen again if there are trailing periods in the title.
